apiVersion: kuadrant.io/v1alpha1
kind: ManagedZone
metadata:
  name: dev-mz-azure
spec:
  id: DUMMY_ID
  domainName: DUMMY_DOMAIN_NAME
  description: "Dev Managed Zone"
  dnsProviderSecretRef:
    name: azure-credentials
