apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kuadrant-dns
resources:
  - namespace.yaml
helmCharts:
  - name: coredns
    repo: https://coredns.github.io/helm
    releaseName: kuadrant
    valuesInline:
      isClusterService: false
      serviceType: LoadBalancer
      prometheus:
        service:
          enabled: true
        monitor:
          enabled: true
          namespace: kuadrant-dns
      image:
        repository: quay.io/kuadrant/coredns-kuadrant
        tag: latest
        pullPolicy: Always
      servers:
        - zones:
            - zone: k.example.com
          port: 53
          plugins:
            - name: debug
            - name: errors
            - name: log
            - name: kuadrant
            - name: prometheus
              parameters: 0.0.0.0:9153
        - zones:
            - zone: f.example.com
          port: 53
          plugins:
            - name: debug
            - name: errors
            - name: log
            - name: file
              parameters: /etc/coredns/f.example.com.db
            - name: prometheus
              parameters: 0.0.0.0:9153
        - zones:
            - zone: example.com
          port: 53
          plugins:
            - name: file
              parameters: /etc/coredns/example.com.db
            - name: cache
              parameters: 10
            - name: prometheus
              parameters: 0.0.0.0:9153
            - name: log
        - zones:
            - zone: .
          port: 53
          plugins:
            - name: whoami
            - name: errors
            # Serves a /health endpoint on :8080, required for livenessProbe
            - name: health
              configBlock: |-
                lameduck 5s
            # Serves a /ready endpoint on :8181, required for readinessProbe
            - name: ready
            # Required to query kubernetes API for data
            # Serves a /metrics endpoint on :9153, required for serviceMonitor
            - name: prometheus
              parameters: 0.0.0.0:9153
            - name: forward
              parameters: . /etc/resolv.conf
            - name: cache
              parameters: 30
            - name: loop
            - name: reload
            - name: log
        - zones:
          namespace: kuadrant-dns
      zoneFiles:
        - filename: f.example.com.db
          domain: f.example.com
          contents: |
            f.example.com.   IN SOA ns1.f.example.com. root.f.example.com. 2015082541 7200 3600 1209600 3600
            f.example.com.   IN NS  ns1.f.example.com.
            f.example.com.   IN NS  ns2.f.example.com.
            rec1.api.f.example.com.   IN A   1.2.3.4
            rec1.api.f.example.com.   IN A   2.3.4.5
            rec2.api.f.example.com.   IN A   3.4.5.6
            rec2.api.f.example.com.   IN A   4.5.6.7
            lb.api.f.example.com.   IN CNAME  rec2.api.f.example.com.
            api.f.example.com.   IN CNAME  lb.api.f.example.com.
            *.api.f.example.com. IN A   9.9.9.9
        - filename: example.com.db
          domain: example.com
          contents: |
            api.example.com. IN SOA ns1.example.com. hostmaster.example.com. 1 7200 900 1209600 86400
            w.api.example.com. IN TXT 100,cluster1.klb.api.example.com
            d.api.example.com. IN TXT us
            api.example.com. IN CNAME klb.api.example.com.
            m.api.example.com. IN CNAME klb.api.example.com.
            klb.api.example.com. in CNAME geo-us.klb.api.example.com.
            geo-us.klb.api.example.com. IN CNAME cluster1.klb.api.example.com.
            cluster1.klb.api.example.com. IN CNAME 81.17.23.10
patches:
  - path: k8s_prometheus_patch.yaml
  - target:
      kind: ClusterRole
      name: kuadrant-coredns
    patch: |
      - op: add
        path: /rules/-
        value:
          apiGroups:
            - kuadrant.io
          resources:
            - dnsrecords
          verbs:
            - get
            - list
            - watch
