apiVersion: kuadrant.io/v1alpha1
kind: DNSRecord
metadata:
  name: combined-loadbalanced-dns
  namespace: dnstest
spec:
  endpoints:
    - dnsName: cluster2.klb.${KUADRANT_SUB_DOMAIN}
      recordTTL: 60
      recordType: A
      targets:
        - 127.0.0.2
    - dnsName: ${KUADRANT_SUB_DOMAIN}
      recordTTL: 300
      recordType: CNAME
      targets:
        - klb.${KUADRANT_SUB_DOMAIN}
    - dnsName: geo-eu.klb.${KUADRANT_SUB_DOMAIN}
      providerSpecific:
        - name: weight
          value: '200'
      recordTTL: 60
      recordType: CNAME
      setIdentifier: cluster2.klb.${KUADRANT_SUB_DOMAIN}
      targets:
        - cluster2.klb.${KUADRANT_SUB_DOMAIN}
    - dnsName: klb.${KUADRANT_SUB_DOMAIN}
      providerSpecific:
        - name: geo-code
          value: GEO-EU
      recordTTL: 300
      recordType: CNAME
      setIdentifier: GEO-EU
      targets:
        - geo-eu.klb.${KUADRANT_SUB_DOMAIN}
  providerRef:
    name: dns-provider-credentials-azure
  rootHost: ${KUADRANT_SUB_DOMAIN}
