
apiVersion: kuadrant.io/v1alpha1
kind: DNSRecord
metadata:
  name: simple-dns
spec:
  endpoints:
    - dnsName: ${KUADRANT_SUB_DOMAIN}
      recordTTL: 60
      recordType: A
      targets:
        - 172.32.200.17
  providerRef:
    name: ${KUADRANT_DNS_PROVIDER_REF}
  rootHost: ${KUADRANT_SUB_DOMAIN}
