apiVersion: kuadrant.io/v1alpha1
kind: DNSRecord
metadata:
  name: simple-dns
spec:
  healthCheck:
    path: "/health"
    port: 80
    protocol: "HTTPS"
    failureThreshold: 3
  endpoints:
    - dnsName: ${KUADRANT_SUB_DOMAIN}
      recordTTL: 60
      recordType: A
      targets:
        - 172.32.200.17
  provider:
    name: ${KUADRANT_DNS_PROVIDER_NAME}
  rootHost: ${KUADRANT_SUB_DOMAIN}
