namespace: kuadrant-coredns-2
nameSuffix: "-2"

resources:
  - ../../coredns-unmonitored

configMapGenerator:
  - name: kuadrant-coredns
    behavior: replace
    files:
      - Corefile

patches:
  - patch: '[{"op": "replace", "path": "/spec/template/spec/containers/0/env/0", "value":
    {"name": "WATCH_NAMESPACES", "value": "kuadrant-coredns-2"}}]'
    target:
      kind: Deployment
