# Local deployment overlay.
#
# Set the deployment imagePullPolicy to IfNotPresent. This is required if you are using a local image loaded into kind i.e. make kind-load-image
#

# TODO: validate azure has the right

resources:
  - ../../default

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom
        value:
        - secretRef:
            name: dns-provider-credentials-aws
            optional: true
    target:
      kind: Deployment
  - path: manager_config_patch.yaml
