namespace: kuadrant-coredns-1
nameSuffix: "-1"

resources:
  - ../../coredns-unmonitored

configMapGenerator:
  - name: kuadrant-coredns
    behavior: replace
    files:
      - Corefile

patches:
  - patch: |-
      $patch: delete
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: kuadrant-coredns
  - patch: '[{"op": "replace", "path": "/spec/template/spec/containers/0/env/0", "value":
    {"name": "WATCH_NAMESPACES", "value": "kuadrant-coredns-1"}}]'
    target:
      kind: Deployment
