apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

# grafana-dashboard dashboards as configmaps
configMapGenerator:
- name: grafana-coredns
  files:
  - ./dashboard.json

generatorOptions:
  disableNameSuffixHash: true
