apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kuadrant-dns-c2
resources:
  - namespace.yaml
  - clusterrolebinding.yaml
helmCharts:
  - name: coredns
    repo: https://coredns.github.io/helm
    releaseName: kuadrant
    valuesInline:
      env:
        - name: WATCH_NAMESPACES
          value: kuadrant-dns-c2
      isClusterService: false
      serviceType: LoadBalancer
      prometheus:
        service:
          enabled: true
        monitor:
          enabled: true
          namespace: kuadrant-dns-c2
      image:
        repository: quay.io/kuadrant/coredns-kuadrant
        tag: latest
        pullPolicy: Always
      servers:
        - zones:
            - zone: k.example.com
          port: 53
          plugins:
            - name: debug
            - name: errors
            - name: log
            - name: kuadrant
            - name: prometheus
              parameters: 0.0.0.0:9153
        - zones:
            - zone: kdrnt
          port: 53
          plugins:
            - name: debug
            - name: errors
            - name: log
            - name: kuadrant
            - name: prometheus
              parameters: 0.0.0.0:9153
        - zones:
            - zone: .
          port: 53
          plugins:
            - name: whoami
            - name: errors
            # Serves a /health endpoint on :8080, required for livenessProbe
            - name: health
              configBlock: |-
                lameduck 5s
            # Serves a /ready endpoint on :8181, required for readinessProbe
            - name: ready
            - name: prometheus
              parameters: 0.0.0.0:9153
            - name: forward
              parameters: . /etc/resolv.conf
            - name: cache
              parameters: 30
            - name: loop
            - name: reload
            - name: log
patches:
  - path: k8s_prometheus_patch.yaml
  - target:
      kind: ClusterRole
      name: kuadrant-coredns
    patch: |
      - op: add
        path: /rules/-
        value:
          apiGroups:
            - kuadrant.io
          resources:
            - dnsrecords
          verbs:
            - get
            - list
            - watch
  - patch: |-
      $patch: delete
      apiVersion: monitoring.coreos.com/v1
      kind: ServiceMonitor
      metadata:
        name: kuadrant-coredns
        namespace: kuadrant-dns-c2
